import Inter from '@next/font/google';
import type { Metadata } from 'next';
import React from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <style>{`.${inter.className} { font-family: ${inter.cssFontFamily}; }`}</style>
      </head>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
